### ISSUE TITLE
Expedition Creation Process

### ISSUE THREAD

**Issue by jdeck88** [biocodellc/geome-ui#191] opened 2018-11-12 21:39 UTC
When creating an expedition in PRODUCTION environment it always says the "expedition name" already exists.

Also, there is an Expedition Code, and Expedition Title field but the error message says that the "Expedition Name" already exists.... is this referring to code or title?  "Name" is amibiguous.

**Comment by rodney757** [comment] 2018-11-13 19:24
The name ambiguity was fixed in d6f6473be3cd2b9d205766c276a7b96f509dbf8e

I can't reproduce the already exists error. Maybe it was fixed w/ the latest deploy. Please re-open if you run into it again.

**Closed by rodney757** 2018-11-13 19:24 UTC
